version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=your_password
      - DATABASE_NAME=fintech_db
      - JWT_SECRET=your_jwt_secret_here
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=fintech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data: